services:
  db:
    image: postgres:16
    container_name: vaxpulse_db
    environment:
      POSTGRES_USER: vaxpulse
      POSTGRES_PASSWORD: vaxpulse_pw
      POSTGRES_DB: vaxpulse
    ports:
      - "5432:5432"
    volumes:
      - vaxpulse_pgdata:/var/lib/postgresql/data

volumes:
  vaxpulse_pgdata:
